# Generated by Django 5.2.1 on 2025-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_data',
            name='f_Age_Verification',
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Age',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_BatchNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Batch_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Batch_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Date_of_Entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Diagnosis',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Diagnosis_ICD10',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_First_Name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Growth',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Last_Name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Mid_Name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_OrganismCode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_OtherResMech',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Patient_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Sex',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_SiteCode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_SiteName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Site_Name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Site_Org',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Site_Pos',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Site_Pre',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Spec_Num',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Spec_Type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Total_batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Urine_ColCt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Ward',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_Ward_Type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_OrgCode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_OrgName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_Post',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_Pre',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_cn_cni',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_ct_ctl',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_ip_ipi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_reco',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_reco_Code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_ars_tz_tzl',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
