# Generated by Django 5.2.1 on 2026-02-18 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tatstepconfig_tatstepconfigupload_and_more'),
        ('home_final', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcordanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_isolates', models.IntegerField(default=0)),
                ('total_pairs', models.IntegerField(default=0)),
                ('concordant_pairs', models.IntegerField(default=0)),
                ('vmd', models.IntegerField(default=0)),
                ('md', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('ast_concordance_rate', models.FloatField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concordance_batch_reports', to='home.batch_table')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('final_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concordance_reports', to='home_final.final_data')),
            ],
        ),
        migrations.CreateModel(
            name='ConcordanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=100)),
                ('isolate_id', models.IntegerField()),
                ('organism', models.CharField(max_length=255)),
                ('antibiotic', models.CharField(max_length=255)),
                ('site_ris', models.CharField(max_length=3)),
                ('ars_ris', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home_final.concordancereport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(fields=('final_data',), name='unique_concordance_per_isolate'),
        ),
    ]
