# Generated by Django 5.2.1 on 2025-10-22 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_antibioticentry',
            name='ab_Date_uploaded_fd',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
