# Generated by Django 5.0.12 on 2025-10-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='final_data',
            constraint=models.UniqueConstraint(fields=('f_AccessionNo', 'f_Batch_Code'), name='unique_final_accession_batch'),
        ),
    ]
