# Generated by Django 5.2.1 on 2026-02-18 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tatstepconfig_step_owner'),
        ('home_final', '0002_concordancereport_concordancedetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concordancereport',
            name='unique_concordance_per_isolate',
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(fields=('batch', 'final_data'), name='unique_concordance_per_isolate_per_batch'),
        ),
    ]
