# Generated by Django 5.2.1 on 2025-10-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0002_final_antibioticentry_ab_date_uploaded_fd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Antibiotic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Retest_Antibiotic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
