# Generated by Django 5.0.12 on 2025-10-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0002_final_data_unique_final_accession_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAntibiotic_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinalAntibioticFile', models.FileField(blank=True, null=True, upload_to='uploads/final/antibiotic/')),
            ],
            options={
                'db_table': 'FinalAntibiotic_upload',
            },
        ),
    ]
