# Generated by Django 5.2.1 on 2025-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0002_remove_final_data_f_age_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_data',
            name='f_edta',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_x_entbac',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_x_mrsamrse',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='final_data',
            name='f_x_mrse',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
