# Generated by Django 5.0.12 on 2025-10-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0003_finalantibiotic_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_data',
            name='f_abx_code',
        ),
    ]
