# Generated by Django 5.2.1 on 2026-02-20 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tatstepconfig_step_owner'),
        ('home_final', '0003_remove_concordancereport_unique_concordance_per_isolate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concordancereport',
            name='unique_concordance_per_isolate_per_batch',
        ),
        migrations.RemoveField(
            model_name='concordancedetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='concordancereport',
            name='final_data',
        ),
        migrations.AddField(
            model_name='concordancedetail',
            name='deviation_code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='concordancedetail',
            name='genus_con',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='concordancedetail',
            name='is_discordant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concordancedetail',
            name='species_con',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='critical_deviation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='critical_deviation_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='total_deviation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='total_deviation_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='concordancereport',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concordance_reports', to='home.batch_table'),
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(fields=('batch',), name='unique_concordance_per_batch'),
        ),
    ]
