# Generated by Django 5.2.1 on 2026-02-25 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tatstepconfig_step_owner'),
        ('home_final', '0004_remove_concordancereport_unique_concordance_per_isolate_per_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concordancereport',
            name='unique_concordance_per_batch',
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='final_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concordance_reports', to='home_final.final_data'),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='report_type',
            field=models.CharField(choices=[('batch', 'Batch'), ('accession', 'Accession')], default='batch', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concordancereport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concordance_reports', to='home.batch_table'),
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'batch')), fields=('batch',), name='unique_batch_concordance'),
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'accession')), fields=('final_data',), name='unique_accession_concordance'),
        ),
    ]
