# Generated by Django 5.2.1 on 2026-02-26 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tatstepconfig_step_owner'),
        ('home_final', '0005_remove_concordancereport_unique_concordance_per_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concordancereport',
            name='unique_batch_concordance',
        ),
        migrations.RemoveConstraint(
            model_name='concordancereport',
            name='unique_accession_concordance',
        ),
        migrations.RemoveField(
            model_name='concordancereport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='genus_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='genus_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='species_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concordancereport',
            name='species_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('final_data__isnull', True)), fields=('batch',), name='unique_batch_concordance'),
        ),
        migrations.AddConstraint(
            model_name='concordancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('final_data__isnull', False)), fields=('final_data',), name='unique_accession_concordance'),
        ),
    ]
