# Generated by Django 5.2.1 on 2026-02-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0006_remove_concordancereport_unique_batch_concordance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Abx_Flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Org_Flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
