# Generated by Django 5.2.1 on 2026-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0007_alter_final_antibioticentry_ab_abx_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Abx_Flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='final_antibioticentry',
            name='ab_Org_Flag',
            field=models.BooleanField(default=False),
        ),
    ]
