# Generated by Django 5.2.1 on 2026-03-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0008_alter_final_antibioticentry_ab_abx_flag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalData_upload',
        ),
    ]
