# Generated by Django 5.2.1 on 2026-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0009_delete_finaldata_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_data',
            name='f_Reason',
            field=models.TextField(choices=[('n/a', 'n/a'), ('a & d', 'a & d'), ('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('o', 'o')], default='n/a', max_length=255),
        ),
    ]
