# Generated by Django 5.2.1 on 2026-06-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0010_alter_final_data_f_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification_table',
            name='Class_Chk_EGASP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classification_table',
            name='Class_Chk_Pulsenet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classification_table',
            name='Class_Chk_Structured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classification_table',
            name='Class_Chk_Tulip',
            field=models.BooleanField(default=False),
        ),
    ]
