# Generated by Django 5.2.1 on 2026-06-11 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_arsstaff_details_staff_credentials_userprofile'),
        ('home_final', '0011_classification_table_class_chk_egasp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concordancereport',
            index=models.Index(fields=['-created_at'], name='concordance_created_idx'),
        ),
    ]
