# Generated by Django 5.2.1 on 2026-06-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0012_concordancereport_concordance_created_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emerging_table',
            old_name='eme_ReferralData',
            new_name='eme_ReferralDate',
        ),
    ]
