# Generated by Django 5.2.1 on 2026-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0013_rename_eme_referraldata_emerging_table_eme_referraldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_data',
            name='f_Age_Display',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
