# Generated by Django 5.2.1 on 2026-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0019_remove_final_antibioticentry_ab_mic_value_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_data',
            name='f_arsp_Rev_Lic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='final_data',
            name='f_arsp_Reviewer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
