# Generated by Django 5.2.1 on 2026-07-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0020_final_data_f_arsp_rev_lic_final_data_f_arsp_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_data',
            name='f_arsp_Rev_Lic',
        ),
        migrations.RemoveField(
            model_name='final_data',
            name='f_arsp_Reviewer',
        ),
    ]
