# Generated by Django 5.2.1 on 2026-08-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0022_remove_unique_final_bat_seq_per_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcordanceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritize_mic', models.BooleanField(default=False)),
                ('no_serotyping', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='home_final.concordancereport')),
            ],
            options={
                'verbose_name_plural': 'Concordance Options',
            },
        ),
    ]
