# Generated by Django 5.2.1 on 2026-08-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0023_concordanceoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concordanceoptions',
            old_name='prioritize_mic',
            new_name='prioritize_disk_site',
        ),
        migrations.AddField(
            model_name='concordanceoptions',
            name='applied_org',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='concordanceoptions',
            name='prioritize_mic_site',
            field=models.BooleanField(default=False),
        ),
    ]
