# Generated by Django 5.2.1 on 2026-08-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_final', '0024_rename_prioritize_mic_concordanceoptions_prioritize_disk_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concordanceoptions',
            name='applied_org_grp',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
