# Generated by Django 5.2.1 on 2026-09-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verificationcomment_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcomment',
            name='resolution_status',
            field=models.CharField(choices=[('open', 'Open'), ('handled', 'Correction applied'), ('resolved', 'Resolved by Verifier'), ('rejected', 'Rejected')], default='open', max_length=30),
        ),
    ]
