# Generated by Django 5.0.12 on 2025-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referred_data',
            constraint=models.UniqueConstraint(fields=('AccessionNo', 'Batch_Code'), name='unique_accession_batch'),
        ),
    ]
