# Generated by Django 5.2.1 on 2026-02-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_table',
            name='bat_Date_Checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch_table',
            name='bat_Date_Encoded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch_table',
            name='bat_Date_Head',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch_table',
            name='bat_Date_LabManager',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch_table',
            name='bat_Date_Verified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
