# Generated by Django 5.2.1 on 2025-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiotic_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_uploadAbx', models.FileField(blank=True, null=True, upload_to='uploads/breakpoints/')),
            ],
            options={
                'db_table': 'Antibiotic_upload',
            },
        ),
    ]
