# Generated by Django 5.0.12 on 2025-10-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakpointstable',
            name='Retest',
        ),
        migrations.RemoveField(
            model_name='breakpointstable',
            name='Show',
        ),
    ]
