# Generated by Django 5.0.12 on 2025-10-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCode_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_uploadSite', models.FileField(blank=True, null=True, upload_to='uploads/site/')),
            ],
            options={
                'db_table': 'SiteCode_upload',
            },
        ),
    ]
