# Generated by Django 5.2.1 on 2025-10-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitecode_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referred_data',
            name='Laboratory_Staff',
        ),
    ]
