# Generated by Django 5.0.12 on 2025-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_breakpointstable_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_operand',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_operand',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
