# Generated by Django 5.2.1 on 2026-02-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_batch_table_bat_date_checked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TATexclusion',
        ),
        migrations.RemoveField(
            model_name='tatform',
            name='Batch_Isolates',
        ),
        migrations.DeleteModel(
            name='TATprocess',
        ),
        migrations.DeleteModel(
            name='TATUpload',
        ),
        migrations.DeleteModel(
            name='TATform',
        ),
    ]
