# Generated by Django 5.2.1 on 2025-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_antibiotic_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibiotic_list',
            name='Tier',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
