# Generated by Django 5.0.12 on 2025-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_antibioticentry_ab_mic_operand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_operand',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_operand',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
