# Generated by Django 5.2.1 on 2025-10-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_referred_data_laboratory_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referred_data',
            name='Con_WGSFastq',
        ),
    ]
