# Generated by Django 5.2.4 on 2025-07-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_f_batch_name_final_data_f_batch_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final_data',
            old_name='Mid_Name',
            new_name='f_Mid_Name',
        ),
    ]
