# Generated by Django 5.2.1 on 2026-02-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_tatexclusion_remove_tatform_batch_isolates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TATStepConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(max_length=100)),
                ('step_owner', models.CharField(choices=[('n/a', 'n/a'), ('LAB', 'LAB'), ('DMU', 'DMU')], default='n/a', max_length=10)),
                ('target_days', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TATStepConfigUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tat_file', models.FileField(blank=True, null=True, upload_to='uploads/TAT/')),
            ],
            options={
                'db_table': 'TATStepConfigUpload',
            },
        ),
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Date_Checked',
        ),
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Date_Encoded',
        ),
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Date_Head',
        ),
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Date_LabManager',
        ),
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Date_Verified',
        ),
        migrations.CreateModel(
            name='TATform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tat_SiteCode', models.CharField(blank=True, max_length=10)),
                ('tat_Batch_Code', models.CharField(blank=True, max_length=255)),
                ('tat_Referral_Date', models.DateField(blank=True, null=True)),
                ('tat_BatchNumber', models.CharField(blank=True, max_length=255)),
                ('tat_Total_Batch', models.CharField(blank=True, max_length=100)),
                ('tat_Num_Isolate', models.PositiveIntegerField(blank=True, null=True)),
                ('tat_Batch_Location', models.CharField(choices=[('LAB', 'LAB'), ('DMU', 'DMU'), ('n/a', 'n/a')], default='n/a', max_length=20)),
                ('tat_Target_Days', models.PositiveIntegerField(blank=True, null=True)),
                ('tat_Date_Released', models.DateField(blank=True, null=True)),
                ('tat_Running_TAT', models.PositiveIntegerField(blank=True, null=True)),
                ('tat_Final_TAT', models.PositiveIntegerField(blank=True, null=True)),
                ('tat_Status_Release', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Released', 'Released'), ('Overdue', 'Overdue')], default='Ongoing', max_length=20)),
                ('tat_Remarks', models.TextField(blank=True, null=True)),
                ('tat_Date_Last_Update', models.DateField(blank=True, null=True)),
                ('tat_Batch_Isolates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tat_entry', to='home.batch_table')),
            ],
            options={
                'db_table': 'TATform',
            },
        ),
        migrations.CreateModel(
            name='TATStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(max_length=100)),
                ('step_owner', models.CharField(blank=True, max_length=10)),
                ('step_days_count', models.PositiveIntegerField(blank=True, null=True)),
                ('within_tat', models.BooleanField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.arsstaff_details')),
                ('tat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.tatform')),
                ('step_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_steps', to='home.tatstepconfig')),
            ],
        ),
    ]
