# Generated by Django 5.2.1 on 2025-10-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_antibiotic_list_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibiotic_list',
            name='Whonet_Abx',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
