# Generated by Django 5.2.1 on 2025-10-23 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_antibiotic_list_whonet_abx'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpointstable',
            name='Antibiotic_list',
            field=models.ForeignKey(blank=True, db_column='Abx_List_Whonet_Abx', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakpoints', to='home.antibiotic_list', to_field='Whonet_Abx'),
        ),
    ]
