# Generated by Django 5.2.4 on 2025-07-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_mid_name_final_data_f_mid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred_data',
            name='Batch_Code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
