# Generated by Django 5.0.12 on 2025-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_antibioticentry_ab_mic_operand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Disk_RIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_RIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_operand',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_Disk_RIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_RIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_operand',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
