# Generated by Django 5.2.1 on 2025-10-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_referred_data_con_wgsfastq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferredData_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReferredDataFile', models.FileField(blank=True, null=True, upload_to='uploads/raw/')),
            ],
        ),
    ]
