# Generated by Django 5.0.12 on 2025-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_antibioticentry_ab_disk_ris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_operand',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_operand',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
