# Generated by Django 5.0.12 on 2025-10-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_referreddata_upload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='breakpoint_upload',
            table='Breakpoint_upload',
        ),
        migrations.AlterModelTable(
            name='breakpointstable',
            table='BreakpointsTable',
        ),
        migrations.AlterModelTable(
            name='final_data',
            table='Final_Data',
        ),
        migrations.AlterModelTable(
            name='referred_data',
            table='Referred_Data',
        ),
        migrations.AlterModelTable(
            name='referreddata_upload',
            table='Referred_upload',
        ),
        migrations.AlterModelTable(
            name='tatform',
            table='TATform',
        ),
        migrations.AlterModelTable(
            name='tatprocess',
            table='TATprocess',
        ),
    ]
