# Generated by Django 5.2.1 on 2025-10-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_breakpointstable_antibiotic_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antibiotic_list',
            old_name='Abx_Code',
            new_name='Abx_code',
        ),
    ]
