# Generated by Django 5.2.1 on 2026-02-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_nonworkingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatstepconfig',
            name='step_type',
            field=models.CharField(max_length=500),
        ),
    ]
