# Generated by Django 5.2.4 on 2025-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_referred_data_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred_data',
            name='RefNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
