# Generated by Django 5.0.12 on 2025-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_antibioticentry_ab_mic_operand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egasp_data',
            name='PermAdd_same_CurrAdd',
            field=models.BooleanField(default=False),
        ),
    ]
