# Generated by Django 5.2.1 on 2025-07-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_referred_data_refno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred_data',
            name='AccessionNo',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
