# Generated by Django 5.2.1 on 2025-10-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_abx_code_antibiotic_list_abx_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibiotic_list',
            name='Date_Modified',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
