# Generated by Django 5.2.1 on 2026-02-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tatstepconfig_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatstepconfig',
            name='step_owner',
            field=models.CharField(choices=[('n/a', 'n/a'), ('LAB', 'LAB'), ('DMU', 'DMU')], default='n/a', max_length=255),
        ),
    ]
