# Generated by Django 5.0.12 on 2025-10-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_breakpoint_upload_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referreddata_upload',
            name='ReferredDataFile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/referred/'),
        ),
    ]
