# Generated by Django 5.2.1 on 2026-03-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tatstepconfig_step_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred_data',
            name='Growth',
            field=models.CharField(blank=True, choices=[('n/a', 'n/a'), ('light growth', 'light growth'), ('light to moderate growth', 'light to moderate growth'), ('moderate growth', 'moderate growth'), ('heavy growth', 'heavy growth'), ('moderately heavy growth', 'moderately heavy growth'), ('positive growth', 'positive growth'), ('no growth', 'no growth')], default='n/a', max_length=255),
        ),
    ]
