# Generated by Django 5.0.12 on 2025-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_egasp_data_permadd_same_curradd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egasp_data',
            name='Age',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='egasp_data',
            name='Sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
