# Generated by Django 5.0.12 on 2025-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_referreddata_upload_referreddatafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred_data',
            name='arsp_Checker',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='arsp_Encoder',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='arsp_Head',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='arsp_LabManager',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='arsp_Verifier',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
