# Generated by Django 5.2.1 on 2025-10-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_antibiotic_list_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibiotic_list',
            name='Guidelines',
            field=models.CharField(blank=True, choices=[('CLSI', 'CLSI')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='antibiotic_list',
            name='Test_Method',
            field=models.CharField(blank=True, choices=[('DISK', 'DISK'), ('MIC', 'MIC')], default='', max_length=100),
        ),
    ]
