# Generated by Django 5.2.1 on 2026-03-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_referred_data_growth'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAntibiotic_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RawAntibioticFile', models.FileField(blank=True, null=True, upload_to='uploads/raw/antibiotic-entries/')),
            ],
            options={
                'db_table': 'RawAntibiotic_upload',
            },
        ),
    ]
