# Generated by Django 5.2.1 on 2026-01-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_referred_data_site_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_table',
            name='bat_seq',
            field=models.PositiveIntegerField(blank=True, help_text='Auto sequence number per batch', null=True),
        ),
    ]
