# Generated by Django 5.2.1 on 2025-08-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_referred_data_accessionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred_data',
            name='Site_NameGen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
