# Generated by Django 5.2.1 on 2026-03-12 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rawantibiotic_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Date_uploaded_rd',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
