# Generated by Django 5.2.1 on 2026-03-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_antibioticentry_ab_date_uploaded_rd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MICValue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
