# Generated by Django 5.2.1 on 2025-08-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_referred_data_site_namegen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_data',
            name='f_Date_Accomplished_ARSP',
        ),
        migrations.RemoveField(
            model_name='final_data',
            name='f_Laboratory_Staff',
        ),
        migrations.RemoveField(
            model_name='final_data',
            name='f_ars_contact',
        ),
        migrations.RemoveField(
            model_name='final_data',
            name='f_ars_email',
        ),
        migrations.RemoveField(
            model_name='final_data',
            name='f_ars_notes',
        ),
        migrations.AddField(
            model_name='lab_staff_details',
            name='LabStaff_License',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Chec_Lic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Checker',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Enc_Lic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Encoder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Head',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Head_Lic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_LabManager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Lab_Lic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Ver_Lic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='arsp_Verifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TATform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_DateRec', models.DateField(blank=True, null=True)),
                ('Target_Days', models.CharField(blank=True, max_length=3)),
                ('Days_Count', models.CharField(blank=True, max_length=3)),
                ('Running_TAT', models.CharField(blank=True, max_length=3)),
                ('Num_Isolate', models.CharField(blank=True, max_length=3)),
                ('Total_Batch', models.CharField(blank=True, max_length=3)),
                ('ars_Encoder', models.CharField(blank=True, max_length=255)),
                ('ars_Checker', models.CharField(blank=True, max_length=255)),
                ('ars_Verifier', models.CharField(blank=True, max_length=255)),
                ('ars_LabManager', models.CharField(blank=True, max_length=255)),
                ('ars_Head', models.CharField(blank=True, max_length=255)),
                ('TAT_Process', models.CharField(blank=True, max_length=255)),
                ('Unit_code', models.CharField(blank=True, max_length=3)),
                ('Batch_Isolates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tat_entries', to='home.referred_data')),
            ],
        ),
    ]
