# Generated by Django 5.2.1 on 2025-08-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_final_data_f_date_accomplished_arsp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TATprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAT_Process', models.CharField(blank=True, max_length=255)),
                ('Unit_code', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='tatform',
            name='TAT_Process',
        ),
        migrations.RemoveField(
            model_name='tatform',
            name='Unit_code',
        ),
    ]
