# Generated by Django 5.2.1 on 2026-03-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_antibioticentry_ab_retest_micvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='is_retest',
            field=models.BooleanField(default=False),
        ),
    ]
