# Generated by Django 5.2.1 on 2026-01-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_batch_table_bat_seq_referred_data_batch_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referred_data',
            name='batch_seq',
        ),
        migrations.AddField(
            model_name='batch_table',
            name='bat_seq',
            field=models.PositiveIntegerField(blank=True, help_text='Auto sequence number per batch', null=True),
        ),
    ]
