# Generated by Django 5.2.1 on 2025-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tatprocess_remove_tatform_tat_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TATUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/TAT/')),
            ],
            options={
                'db_table': 'TATUpload',
            },
        ),
    ]
