# Generated by Django 5.2.1 on 2025-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tatupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_data',
            name='f_Total_batch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referred_data',
            name='Total_batch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
