# Generated by Django 5.2.1 on 2026-06-04 06:27

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_referred_data_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='Site_Address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Lab_Head',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Lab_Head_Contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Lab_Head_Designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Lab_Head_Email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_MedTech',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_MedTech_Contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_MedTech_Designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_MedTech_Email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Med_Ctr_Chief',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Med_Ctr_Chief_Contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Med_Ctr_Chief_Designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Site_Med_Ctr_Chief_Email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
