# Generated by Django 5.2.1 on 2026-01-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_batch_table_bat_seq_referred_data_bat_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Disk_Abx',
            field=models.BooleanField(default=False),
        ),
    ]
