# Generated by Django 5.2.1 on 2026-01-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_antibioticentry_ab_disk_abx'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Ret_Disk_Abx',
            field=models.BooleanField(default=False),
        ),
    ]
