# Generated by Django 5.2.1 on 2025-08-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_final_data_f_total_batch_referred_data_total_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred_data',
            name='Status',
            field=models.CharField(choices=[('n/a', ''), ('Encoding', 'Encoding'), ('First Draft', '1st Draft'), ('Second Draft', '2nd Draft'), ('Third Draft', '3rd Draft'), ('Verification', 'Verification'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tatform',
            name='AccessionNum',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
