# Generated by Django 5.2.1 on 2026-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sitedata_site_address_sitedata_site_lab_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_MIC_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='antibioticentry',
            name='ab_Retest_MICValue',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
