# Generated by Django 5.2.1 on 2025-08-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_referred_data_status_tatform_accessionnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lab_Staff_Details',
            new_name='arsStaff_Details',
        ),
        migrations.RenameField(
            model_name='arsstaff_details',
            old_name='LabStaff_Designation',
            new_name='Staff_Designation',
        ),
        migrations.RenameField(
            model_name='arsstaff_details',
            old_name='LabStaff_EmailAdd',
            new_name='Staff_EmailAdd',
        ),
        migrations.RenameField(
            model_name='arsstaff_details',
            old_name='LabStaff_License',
            new_name='Staff_License',
        ),
        migrations.RenameField(
            model_name='arsstaff_details',
            old_name='LabStaff_Name',
            new_name='Staff_Name',
        ),
        migrations.RenameField(
            model_name='arsstaff_details',
            old_name='LabStaff_Telnum',
            new_name='Staff_Telnum',
        ),
    ]
