# Generated by Django 5.2.1 on 2026-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_antibioticentry_ab_mic_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsstaff_details',
            name='Staff_Role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
