# Generated by Django 5.2.1 on 2026-01-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_antibioticentry_ab_ret_disk_abx'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibiotic_list',
            name='Show_Print',
            field=models.BooleanField(default=True),
        ),
    ]
