# Generated by Django 5.2.1 on 2026-01-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_antibiotic_list_show_print'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antibiotic_list',
            old_name='Show_Print',
            new_name='Show_Final',
        ),
    ]
