# Generated by Django 5.2.1 on 2025-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_lab_staff_details_arsstaff_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Disk_enRIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_MIC_enRIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Retest_Dis_enRIS',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Retest_MIC_enRIS',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
