# Generated by Django 5.2.1 on 2026-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_arsstaff_details_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsstaff_details',
            name='Staff_Role',
            field=models.CharField(blank=True, choices=[('', ''), ('Encoder', 'Encoder'), ('Verifier', 'Verifier'), ('Checker', 'Checker'), ('Admin', 'Admin')], default='', max_length=150),
        ),
    ]
