# Generated by Django 5.2.1 on 2026-06-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_arsstaff_details_staff_credentials_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referred_data',
            name='Site_Pos',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='Site_Pre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='ars_Post',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='referred_data',
            name='ars_Pre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
