# Generated by Django 5.2.1 on 2026-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_referred_data_site_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referred_data',
            name='Age_Display',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
