# Generated by Django 5.2.1 on 2026-07-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_backfill_bat_seq_from_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_MIC_value_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='antibioticentry',
            name='ab_Retest_MICValue_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
