# Generated by Django 5.2.1 on 2026-07-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_antibioticentry_ab_mic_value_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibioticentry',
            name='ab_MIC_value_str',
        ),
        migrations.RemoveField(
            model_name='antibioticentry',
            name='ab_Retest_MICValue_str',
        ),
    ]
