# Generated by Django 5.2.1 on 2026-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_antibioticentry_ab_mic_value_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatform',
            name='tat_Scanning_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tatform',
            name='tat_Scanning_raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tatform',
            name='tat_Scanning_ws',
            field=models.BooleanField(default=False),
        ),
    ]
