# Generated by Django 5.2.1 on 2026-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_tatform_tat_scanning_final_tatform_tat_scanning_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_table',
            name='bat_Rev_Lic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='batch_table',
            name='bat_Reviewer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='arsstaff_details',
            name='Staff_Role',
            field=models.CharField(blank=True, choices=[('', ''), ('Encoder', 'Encoder'), ('Verifier', 'Verifier'), ('Checker', 'Checker'), ('Lab Manager', 'Lab Manager'), ('Admin', 'Admin')], default='', max_length=150),
        ),
    ]
