# Generated by Django 5.2.1 on 2026-07-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_batch_table_bat_rev_lic_batch_table_bat_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Rev_Lic',
        ),
        migrations.RemoveField(
            model_name='batch_table',
            name='bat_Reviewer',
        ),
    ]
