# Generated by Django 5.2.1 on 2026-07-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_tatstep_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpointstable',
            name='Org_Code_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
