# Generated by Django 5.2.1 on 2026-08-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_tatlocation_alter_tatform_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibiotic_list',
            name='Show_All',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='antibiotic_list',
            name='Show_Panel',
            field=models.BooleanField(default=False),
        ),
    ]
