# Generated by Django 5.2.1 on 2026-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_antibiotic_list_show_all_antibiotic_list_show_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibiotic_list',
            name='Method_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organism_list',
            name='No_serotyping',
            field=models.BooleanField(default=False),
        ),
    ]
