# Generated by Django 5.2.1 on 2026-08-20 02:52

from django.db import migrations, models


def seed_overall_tat_setting(apps, schema_editor):
    TATOverallSetting = apps.get_model("home", "TATOverallSetting")
    TATform = apps.get_model("home", "TATform")

    target_days = 40
    existing_target = (
        TATform.objects
        .exclude(tat_Target_Days__isnull=True)
        .exclude(tat_Target_Days=0)
        .values("tat_Target_Days")
        .annotate(count=models.Count("id"))
        .order_by("-count", "tat_Target_Days")
        .first()
    )
    if existing_target:
        target_days = existing_target["tat_Target_Days"]

    TATOverallSetting.objects.update_or_create(
        pk=1,
        defaults={"target_days": target_days},
    )
    TATform.objects.update(tat_Target_Days=target_days)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_antibiotic_list_method_specific_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TATOverallSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_days', models.PositiveIntegerField(default=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TAT Overall Setting',
                'verbose_name_plural': 'TAT Overall Settings',
                'db_table': 'TATOverallSetting',
            },
        ),
        migrations.RunPython(seed_overall_tat_setting, migrations.RunPython.noop),
    ]
