# Generated by Django 5.2.1 on 2026-08-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_tatoverallsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibiotic_list',
            name='Method_specific',
        ),
        migrations.RemoveField(
            model_name='organism_list',
            name='No_serotyping',
        ),
    ]
