# Generated by Codex on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_antibiotic_list_method_specific_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonworkingday',
            name='is_recurring',
            field=models.BooleanField(
                default=False,
                help_text='Apply this non-working day every year using the same month and day.',
            ),
        ),
    ]
