# Generated by Django 5.2.1 on 2025-09-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgs_project',
            name='WGS_Checkm2Summary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='wgs_project',
            name='WGS_Checkm2_Acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
