# Generated by Django 5.2.1 on 2025-10-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wgs_project',
            name='WGS_MlstSummary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
