# Generated by Django 5.2.1 on 2025-10-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0002_alter_wgs_project_wgs_mlstsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastqsummary',
            old_name='Date_uploaded',
            new_name='Date_uploaded_f',
        ),
        migrations.AddField(
            model_name='amrfinderplus',
            name='Date_uploaded_am',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assemblyscan',
            name='Date_uploaded_as',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkm2',
            name='Date_uploaded_c',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gambit',
            name='Date_uploaded_g',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mlst',
            name='Date_uploaded_m',
            field=models.DateField(auto_now=True),
        ),
    ]
