# Generated by Django 5.2.1 on 2025-09-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0002_wgs_project_wgs_checkm2summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkm2',
            name='Checkm2_Accession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkm2',
            name='checkm2_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkm2_entries', to='wgs_app.wgs_project'),
        ),
    ]
