# Generated by Django 5.2.1 on 2026-03-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0002_bactscoutupload_gtdbtkupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleinfo', models.FileField(blank=True, null=True, upload_to='uploads/wgs/bactscout/')),
            ],
            options={
                'db_table': 'SampleInfoUpload',
            },
        ),
    ]
