# Generated by Django 5.2.1 on 2025-09-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0003_checkm2_checkm2_accession_checkm2_checkm2_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyscan',
            name='Assembly_Accession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assemblyscan',
            name='assembly_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_entries', to='wgs_app.wgs_project'),
        ),
        migrations.AddField(
            model_name='wgs_project',
            name='WGS_AssemblySummary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='wgs_project',
            name='WGS_Assembly_Acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
