# Generated by Django 5.2.1 on 2026-03-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0003_sampleinfoupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bactscout',
            name='sample_name',
        ),
    ]
