# Generated by Django 5.2.1 on 2025-10-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0004_assemblyscan_assembly_accession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrfinderplus',
            name='Amrfinder_Accession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amrfinderplus',
            name='amrfinder_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amrfinder_entries', to='wgs_app.wgs_project'),
        ),
    ]
