# Generated by Django 5.2.1 on 2026-03-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0004_remove_bactscout_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinformation',
            name='sample_accession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
