# Generated by Django 5.2.1 on 2025-10-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0005_amrfinderplus_amrfinder_accession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgs_project',
            name='WGS_AmrfinderSummary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='wgs_project',
            name='WGS_Amrfinder_Acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
