# Generated by Django 5.2.1 on 2026-03-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0005_sampleinformation_sample_accession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bactscout',
            old_name='batch_code',
            new_name='name',
        ),
    ]
