# Generated by Django 5.2.1 on 2026-03-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0006_rename_batch_code_bactscout_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemogsData_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemogsDataFile', models.FileField(blank=True, null=True, upload_to='uploads/final/')),
            ],
            options={
                'db_table': 'DemogsData_upload',
            },
        ),
    ]
