# Generated by Django 5.2.1 on 2025-10-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0006_wgs_project_wgs_amrfindersummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastqsummary',
            name='Date_uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
