# Generated by Django 5.2.1 on 2026-06-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0007_demogsdata_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastqsummary',
            name='fastq_project',
        ),
        migrations.DeleteModel(
            name='FastqUpload',
        ),
        migrations.RemoveField(
            model_name='wgs_project',
            name='WGS_FastQ_Acc',
        ),
        migrations.RemoveField(
            model_name='wgs_project',
            name='WGS_FastqSummary',
        ),
        migrations.DeleteModel(
            name='FastqSummary',
        ),
    ]
