# Generated by Django 5.2.1 on 2026-06-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0008_remove_fastqsummary_fastq_project_delete_fastqupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amrfinderplus',
            name='Amrfinder_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assemblyscan',
            name='Assembly_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bactscout',
            name='BactScout_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkm2',
            name='Checkm2_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gambit',
            name='Gambit_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gtdbtk',
            name='GtdbTk_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlst',
            name='Mlst_Accession',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
