# Generated by Django 5.2.1 on 2026-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0009_alter_amrfinderplus_amrfinder_accession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bactscout',
            name='genome_size_expected_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
