# Generated by Django 5.2.1 on 2026-06-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0010_bactscout_genome_size_expected_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bactscout',
            name='species_abundance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bactscout',
            name='species_coverage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
