# Generated by Django 5.2.1 on 2026-08-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0012_sampleinformation_ghru_all_ghru_neo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinformation',
            name='DNA_extraction',
            field=models.BooleanField(blank=True, db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='sampleinformation',
            name='dna_performed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleinformation',
            name='dna_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampleinformation',
            name='library_performed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sampleinformation',
            name='library_performed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampleinformation',
            name='library_preparation',
            field=models.BooleanField(blank=True, db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='sampleinformation',
            name='sequencing_platform',
            field=models.BooleanField(blank=True, db_default=False, default=False),
        ),
    ]
