# Generated by Django 5.2.1 on 2026-08-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgs_app', '0017_custom_pipeline_editable_platform'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customwgspipelinerecord',
            new_name='custom_wgs__pipelin_a90caf_idx',
            old_name='custom_wgs_pipeline_rec_acc_idx',
        ),
        migrations.RenameIndex(
            model_name='customwgspipelinerecord',
            new_name='custom_wgs__pipelin_ff5fe9_idx',
            old_name='custom_wgs_pipeline_rec_match_idx',
        ),
    ]
